// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;

namespace DoctorVanGogh.ReclaimReuseRecycle {
	[GeneratedCode("Defs.Generated.tt","0.1")]
	[SuppressMessage("ReSharper", "InconsistentNaming")]
	[SuppressMessage("ReSharper", "UnusedMember.Global")]
	[SuppressMessage("ReSharper", "ConvertToAutoProperty")]
	[SuppressMessage("ReSharper", "FieldCanBeMadeReadOnly.Local")]
	[SuppressMessage("ReSharper", "ConvertPropertyToExpressionBody")]
	public partial class DefNames {
		public const string @Recipe_ButcherCorpseFlesh = @"ButcherCorpseFlesh";
		public const string @Recipe_ButcherCorpseMechanoid = @"ButcherCorpseMechanoid";
		public const string @Recipe_R3_HarvestCorpseFlesh_Advanced = @"R3_HarvestCorpseFlesh_Advanced";
		public const string @Recipe_R3_HarvestCorpseFlesh_Glittertech = @"R3_HarvestCorpseFlesh_Glittertech";
		public const string @Recipe_R3_HarvestCorpseFlesh_Primitive = @"R3_HarvestCorpseFlesh_Primitive";
		public const string @Recipe_R3_HarvestCorpseMechanoid_Advanced = @"R3_HarvestCorpseMechanoid_Advanced";
		public const string @Recipe_R3_HarvestCorpseMechanoid_Glittertech = @"R3_HarvestCorpseMechanoid_Glittertech";
		public const string @Recipe_R3_HarvestCorpseMechanoid_Primitive = @"R3_HarvestCorpseMechanoid_Primitive";
		public const string @Recipe_R3_Refurbish_Advanced = @"R3_Refurbish_Advanced";
		public const string @Recipe_R3_Refurbish_Glittertech = @"R3_Refurbish_Glittertech";
		public const string @Recipe_R3_Refurbish_Primitive = @"R3_Refurbish_Primitive";
		public const string @Recipe_R3_Sterilize_Advanced = @"R3_Sterilize_Advanced";
		public const string @Recipe_R3_Sterilize_Glittertech = @"R3_Sterilize_Glittertech";
		public const string @Recipe_R3_Sterilize_Primitive = @"R3_Sterilize_Primitive";
		public const string @SpecialThingFilter_R3_AllowUnharvested_Advanced = @"R3_AllowUnharvested_Advanced";
		public const string @SpecialThingFilter_R3_AllowUnharvested_Glittertech = @"R3_AllowUnharvested_Glittertech";
		public const string @SpecialThingFilter_R3_AllowUnharvested_Primitive = @"R3_AllowUnharvested_Primitive";
		public const string @Stat_Beauty = @"Beauty";
		public const string @Stat_DeteriorationRate = @"DeteriorationRate";
		public const string @Stat_Flammability = @"Flammability";
		public const string @Stat_MarketValue = @"MarketValue";
		public const string @Stat_Mass = @"Mass";
		public const string @Stat_MaxHitPoints = @"MaxHitPoints";
		public const string @StatCategory_Basics = @"Basics";
		public const string @StatCategory_ReclaimedItem = @"ReclaimedItem";
		public const string @ThingCategory_BodyParts = @"BodyParts";
		public const string @ThingCategory_BodyPartsMangled = @"BodyPartsMangled";
		public const string @ThingCategory_BodyPartsMangled_Advanced = @"BodyPartsMangled_Advanced";
		public const string @ThingCategory_BodyPartsMangled_Glittertech = @"BodyPartsMangled_Glittertech";
		public const string @ThingCategory_BodyPartsMangled_Primitive = @"BodyPartsMangled_Primitive";
		public const string @ThingCategory_BodyPartsNatural = @"BodyPartsNatural";
		public const string @ThingCategory_BodyPartsNonSterile = @"BodyPartsNonSterile";
		public const string @ThingCategory_BodyPartsNonSterile_Advanced = @"BodyPartsNonSterile_Advanced";
		public const string @ThingCategory_BodyPartsNonSterile_Glittertech = @"BodyPartsNonSterile_Glittertech";
		public const string @ThingCategory_BodyPartsNonSterile_Primitive = @"BodyPartsNonSterile_Primitive";
		public const string @ThingCategory_BodyPartsReclaimed = @"BodyPartsReclaimed";
	}
	[GeneratedCode("Defs.Generated.tt","0.1")]
	[SuppressMessage("ReSharper", "InconsistentNaming")]
	[SuppressMessage("ReSharper", "UnusedMember.Global")]
	[SuppressMessage("ReSharper", "ConvertToAutoProperty")]
	[SuppressMessage("ReSharper", "FieldCanBeMadeReadOnly.Local")]
	[SuppressMessage("ReSharper", "ConvertPropertyToExpressionBody")]
	public partial class DefReferences {
		private static RimWorld.StatCategoryDef _StatCategory_Basics = Verse.DefDatabase<RimWorld.StatCategoryDef>.GetNamed(DefNames.StatCategory_Basics);
		private static RimWorld.StatDef _Stat_Beauty = Verse.DefDatabase<RimWorld.StatDef>.GetNamed(DefNames.Stat_Beauty);
		private static Verse.ThingCategoryDef _ThingCategory_BodyParts = Verse.DefDatabase<Verse.ThingCategoryDef>.GetNamed(DefNames.ThingCategory_BodyParts);
		private static Verse.ThingCategoryDef _ThingCategory_BodyPartsMangled = Verse.DefDatabase<Verse.ThingCategoryDef>.GetNamed(DefNames.ThingCategory_BodyPartsMangled);
		private static Verse.ThingCategoryDef _ThingCategory_BodyPartsMangled_Advanced = Verse.DefDatabase<Verse.ThingCategoryDef>.GetNamed(DefNames.ThingCategory_BodyPartsMangled_Advanced);
		private static Verse.ThingCategoryDef _ThingCategory_BodyPartsMangled_Glittertech = Verse.DefDatabase<Verse.ThingCategoryDef>.GetNamed(DefNames.ThingCategory_BodyPartsMangled_Glittertech);
		private static Verse.ThingCategoryDef _ThingCategory_BodyPartsMangled_Primitive = Verse.DefDatabase<Verse.ThingCategoryDef>.GetNamed(DefNames.ThingCategory_BodyPartsMangled_Primitive);
		private static Verse.ThingCategoryDef _ThingCategory_BodyPartsNatural = Verse.DefDatabase<Verse.ThingCategoryDef>.GetNamed(DefNames.ThingCategory_BodyPartsNatural);
		private static Verse.ThingCategoryDef _ThingCategory_BodyPartsNonSterile = Verse.DefDatabase<Verse.ThingCategoryDef>.GetNamed(DefNames.ThingCategory_BodyPartsNonSterile);
		private static Verse.ThingCategoryDef _ThingCategory_BodyPartsNonSterile_Advanced = Verse.DefDatabase<Verse.ThingCategoryDef>.GetNamed(DefNames.ThingCategory_BodyPartsNonSterile_Advanced);
		private static Verse.ThingCategoryDef _ThingCategory_BodyPartsNonSterile_Glittertech = Verse.DefDatabase<Verse.ThingCategoryDef>.GetNamed(DefNames.ThingCategory_BodyPartsNonSterile_Glittertech);
		private static Verse.ThingCategoryDef _ThingCategory_BodyPartsNonSterile_Primitive = Verse.DefDatabase<Verse.ThingCategoryDef>.GetNamed(DefNames.ThingCategory_BodyPartsNonSterile_Primitive);
		private static Verse.ThingCategoryDef _ThingCategory_BodyPartsReclaimed = Verse.DefDatabase<Verse.ThingCategoryDef>.GetNamed(DefNames.ThingCategory_BodyPartsReclaimed);
		private static Verse.RecipeDef _Recipe_ButcherCorpseFlesh = Verse.DefDatabase<Verse.RecipeDef>.GetNamed(DefNames.Recipe_ButcherCorpseFlesh);
		private static Verse.RecipeDef _Recipe_ButcherCorpseMechanoid = Verse.DefDatabase<Verse.RecipeDef>.GetNamed(DefNames.Recipe_ButcherCorpseMechanoid);
		private static RimWorld.StatDef _Stat_DeteriorationRate = Verse.DefDatabase<RimWorld.StatDef>.GetNamed(DefNames.Stat_DeteriorationRate);
		private static RimWorld.StatDef _Stat_Flammability = Verse.DefDatabase<RimWorld.StatDef>.GetNamed(DefNames.Stat_Flammability);
		private static RimWorld.StatDef _Stat_MarketValue = Verse.DefDatabase<RimWorld.StatDef>.GetNamed(DefNames.Stat_MarketValue);
		private static RimWorld.StatDef _Stat_Mass = Verse.DefDatabase<RimWorld.StatDef>.GetNamed(DefNames.Stat_Mass);
		private static RimWorld.StatDef _Stat_MaxHitPoints = Verse.DefDatabase<RimWorld.StatDef>.GetNamed(DefNames.Stat_MaxHitPoints);
		private static Verse.SpecialThingFilterDef _SpecialThingFilter_R3_AllowUnharvested_Advanced = Verse.DefDatabase<Verse.SpecialThingFilterDef>.GetNamed(DefNames.SpecialThingFilter_R3_AllowUnharvested_Advanced);
		private static Verse.SpecialThingFilterDef _SpecialThingFilter_R3_AllowUnharvested_Glittertech = Verse.DefDatabase<Verse.SpecialThingFilterDef>.GetNamed(DefNames.SpecialThingFilter_R3_AllowUnharvested_Glittertech);
		private static Verse.SpecialThingFilterDef _SpecialThingFilter_R3_AllowUnharvested_Primitive = Verse.DefDatabase<Verse.SpecialThingFilterDef>.GetNamed(DefNames.SpecialThingFilter_R3_AllowUnharvested_Primitive);
		private static Verse.RecipeDef _Recipe_R3_HarvestCorpseFlesh_Advanced = Verse.DefDatabase<Verse.RecipeDef>.GetNamed(DefNames.Recipe_R3_HarvestCorpseFlesh_Advanced);
		private static Verse.RecipeDef _Recipe_R3_HarvestCorpseFlesh_Glittertech = Verse.DefDatabase<Verse.RecipeDef>.GetNamed(DefNames.Recipe_R3_HarvestCorpseFlesh_Glittertech);
		private static Verse.RecipeDef _Recipe_R3_HarvestCorpseFlesh_Primitive = Verse.DefDatabase<Verse.RecipeDef>.GetNamed(DefNames.Recipe_R3_HarvestCorpseFlesh_Primitive);
		private static Verse.RecipeDef _Recipe_R3_HarvestCorpseMechanoid_Advanced = Verse.DefDatabase<Verse.RecipeDef>.GetNamed(DefNames.Recipe_R3_HarvestCorpseMechanoid_Advanced);
		private static Verse.RecipeDef _Recipe_R3_HarvestCorpseMechanoid_Glittertech = Verse.DefDatabase<Verse.RecipeDef>.GetNamed(DefNames.Recipe_R3_HarvestCorpseMechanoid_Glittertech);
		private static Verse.RecipeDef _Recipe_R3_HarvestCorpseMechanoid_Primitive = Verse.DefDatabase<Verse.RecipeDef>.GetNamed(DefNames.Recipe_R3_HarvestCorpseMechanoid_Primitive);
		private static Verse.RecipeDef _Recipe_R3_Refurbish_Advanced = Verse.DefDatabase<Verse.RecipeDef>.GetNamed(DefNames.Recipe_R3_Refurbish_Advanced);
		private static Verse.RecipeDef _Recipe_R3_Refurbish_Glittertech = Verse.DefDatabase<Verse.RecipeDef>.GetNamed(DefNames.Recipe_R3_Refurbish_Glittertech);
		private static Verse.RecipeDef _Recipe_R3_Refurbish_Primitive = Verse.DefDatabase<Verse.RecipeDef>.GetNamed(DefNames.Recipe_R3_Refurbish_Primitive);
		private static Verse.RecipeDef _Recipe_R3_Sterilize_Advanced = Verse.DefDatabase<Verse.RecipeDef>.GetNamed(DefNames.Recipe_R3_Sterilize_Advanced);
		private static Verse.RecipeDef _Recipe_R3_Sterilize_Glittertech = Verse.DefDatabase<Verse.RecipeDef>.GetNamed(DefNames.Recipe_R3_Sterilize_Glittertech);
		private static Verse.RecipeDef _Recipe_R3_Sterilize_Primitive = Verse.DefDatabase<Verse.RecipeDef>.GetNamed(DefNames.Recipe_R3_Sterilize_Primitive);
		private static RimWorld.StatCategoryDef _StatCategory_ReclaimedItem = Verse.DefDatabase<RimWorld.StatCategoryDef>.GetNamed(DefNames.StatCategory_ReclaimedItem);
		public static RimWorld.StatCategoryDef @StatCategory_Basics { get { return _StatCategory_Basics; } }
		public static RimWorld.StatDef @Stat_Beauty { get { return _Stat_Beauty; } }
		public static Verse.ThingCategoryDef @ThingCategory_BodyParts { get { return _ThingCategory_BodyParts; } }
		public static Verse.ThingCategoryDef @ThingCategory_BodyPartsMangled { get { return _ThingCategory_BodyPartsMangled; } }
		public static Verse.ThingCategoryDef @ThingCategory_BodyPartsMangled_Advanced { get { return _ThingCategory_BodyPartsMangled_Advanced; } }
		public static Verse.ThingCategoryDef @ThingCategory_BodyPartsMangled_Glittertech { get { return _ThingCategory_BodyPartsMangled_Glittertech; } }
		public static Verse.ThingCategoryDef @ThingCategory_BodyPartsMangled_Primitive { get { return _ThingCategory_BodyPartsMangled_Primitive; } }
		public static Verse.ThingCategoryDef @ThingCategory_BodyPartsNatural { get { return _ThingCategory_BodyPartsNatural; } }
		public static Verse.ThingCategoryDef @ThingCategory_BodyPartsNonSterile { get { return _ThingCategory_BodyPartsNonSterile; } }
		public static Verse.ThingCategoryDef @ThingCategory_BodyPartsNonSterile_Advanced { get { return _ThingCategory_BodyPartsNonSterile_Advanced; } }
		public static Verse.ThingCategoryDef @ThingCategory_BodyPartsNonSterile_Glittertech { get { return _ThingCategory_BodyPartsNonSterile_Glittertech; } }
		public static Verse.ThingCategoryDef @ThingCategory_BodyPartsNonSterile_Primitive { get { return _ThingCategory_BodyPartsNonSterile_Primitive; } }
		public static Verse.ThingCategoryDef @ThingCategory_BodyPartsReclaimed { get { return _ThingCategory_BodyPartsReclaimed; } }
		public static Verse.RecipeDef @Recipe_ButcherCorpseFlesh { get { return _Recipe_ButcherCorpseFlesh; } }
		public static Verse.RecipeDef @Recipe_ButcherCorpseMechanoid { get { return _Recipe_ButcherCorpseMechanoid; } }
		public static RimWorld.StatDef @Stat_DeteriorationRate { get { return _Stat_DeteriorationRate; } }
		public static RimWorld.StatDef @Stat_Flammability { get { return _Stat_Flammability; } }
		public static RimWorld.StatDef @Stat_MarketValue { get { return _Stat_MarketValue; } }
		public static RimWorld.StatDef @Stat_Mass { get { return _Stat_Mass; } }
		public static RimWorld.StatDef @Stat_MaxHitPoints { get { return _Stat_MaxHitPoints; } }
		public static Verse.SpecialThingFilterDef @SpecialThingFilter_R3_AllowUnharvested_Advanced { get { return _SpecialThingFilter_R3_AllowUnharvested_Advanced; } }
		public static Verse.SpecialThingFilterDef @SpecialThingFilter_R3_AllowUnharvested_Glittertech { get { return _SpecialThingFilter_R3_AllowUnharvested_Glittertech; } }
		public static Verse.SpecialThingFilterDef @SpecialThingFilter_R3_AllowUnharvested_Primitive { get { return _SpecialThingFilter_R3_AllowUnharvested_Primitive; } }
		public static Verse.RecipeDef @Recipe_R3_HarvestCorpseFlesh_Advanced { get { return _Recipe_R3_HarvestCorpseFlesh_Advanced; } }
		public static Verse.RecipeDef @Recipe_R3_HarvestCorpseFlesh_Glittertech { get { return _Recipe_R3_HarvestCorpseFlesh_Glittertech; } }
		public static Verse.RecipeDef @Recipe_R3_HarvestCorpseFlesh_Primitive { get { return _Recipe_R3_HarvestCorpseFlesh_Primitive; } }
		public static Verse.RecipeDef @Recipe_R3_HarvestCorpseMechanoid_Advanced { get { return _Recipe_R3_HarvestCorpseMechanoid_Advanced; } }
		public static Verse.RecipeDef @Recipe_R3_HarvestCorpseMechanoid_Glittertech { get { return _Recipe_R3_HarvestCorpseMechanoid_Glittertech; } }
		public static Verse.RecipeDef @Recipe_R3_HarvestCorpseMechanoid_Primitive { get { return _Recipe_R3_HarvestCorpseMechanoid_Primitive; } }
		public static Verse.RecipeDef @Recipe_R3_Refurbish_Advanced { get { return _Recipe_R3_Refurbish_Advanced; } }
		public static Verse.RecipeDef @Recipe_R3_Refurbish_Glittertech { get { return _Recipe_R3_Refurbish_Glittertech; } }
		public static Verse.RecipeDef @Recipe_R3_Refurbish_Primitive { get { return _Recipe_R3_Refurbish_Primitive; } }
		public static Verse.RecipeDef @Recipe_R3_Sterilize_Advanced { get { return _Recipe_R3_Sterilize_Advanced; } }
		public static Verse.RecipeDef @Recipe_R3_Sterilize_Glittertech { get { return _Recipe_R3_Sterilize_Glittertech; } }
		public static Verse.RecipeDef @Recipe_R3_Sterilize_Primitive { get { return _Recipe_R3_Sterilize_Primitive; } }
		public static RimWorld.StatCategoryDef @StatCategory_ReclaimedItem { get { return _StatCategory_ReclaimedItem; } }
	}
}
