// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;

namespace DoctorVanGogh.ReclaimReuseRecycle {
    [GeneratedCode("DefGenerator.tt","0.1")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
	public static partial class LanguageKeys {
		public static class @r3 {
			/// <summary>
			/// Get's the translation key for '<em>Reclaim, Reuse, Recycle</em>'
			/// </summary>
			public const string @R3_SettingsCategory = "R3.SettingsCategory";
			/// <summary>
			/// Get's the translation key for '<em>&quot;Don’t throw away, recycle for another day.&quot;</em>'
			/// </summary>
			public const string @R3_Tagline = "R3.Tagline";
			/// <summary>
			/// Get's the translation key for '<em>Original item</em>'
			/// </summary>
			public const string @R3_OriginalThing = "R3.OriginalThing";
			/// <summary>
			/// Get's the translation key for '<em>&lt;color=#aaffaaff&gt;non-sterile {0}&lt;/color&gt;</em>'
			/// </summary>
			public const string @R3_NonSterile_Label = "R3.NonSterile.Label";
			/// <summary>
			/// Get's the translation key for '<em>This is a {0} that was reclaimed from a corpse. It needs to be sterilized before it can be used again.</em>'
			/// </summary>
			public const string @R3_NonSterile_Description = "R3.NonSterile.Description";
			/// <summary>
			/// Get's the translation key for '<em>&lt;color=#ffffaaff&gt;mangled {0}&lt;/color&gt;</em>'
			/// </summary>
			public const string @R3_Mangled_Label = "R3.Mangled.Label";
			/// <summary>
			/// Get's the translation key for '<em>This is a {0} that was reclaimed from a corpse. It is heavily damaged and need extensive refurbishment and sterilization before it can be used again.</em>'
			/// </summary>
			public const string @R3_Mangled_Description = "R3.Mangled.Description";
			/// <summary>
			/// Get's the translation key for '<em>Multiplier for reclamation status</em>'
			/// </summary>
			public const string @R3_StatsReport_ReclamationMultiplier = "R3.StatsReport_ReclamationMultiplier";
			/// <summary>
			/// Get's the translation key for '<em>The following settings control the health range(s) a corpse&apos;s part needs to have to be recoverable as the respective item type.<br />&lt;size=12&gt;&lt;i&gt;&lt;color=#808080ff&gt;(The recovered parts will have 100% of their hitpoints when harvested at the top end of the range and 50% hitpoints at the bottom.)&lt;/color&gt;&lt;/i&gt;&lt;/size&gt;</em>'
			/// </summary>
			public const string @R3_RangeExplanation = "R3.RangeExplanation";
			/// <summary>
			/// Get's the translation key for '<em>Health %: {0}</em>'
			/// </summary>
			public const string @R3_HealthRange = "R3.HealthRange";
			/// <summary>
			/// Get's the translation key for '<em>Recoverable as a &lt;b&gt;&lt;color=#ffffaaff&gt;Mangled&lt;/color&gt;&lt;/b&gt; item</em>'
			/// </summary>
			public const string @R3_Mangled_Settings = "R3.Mangled.Settings";
			/// <summary>
			/// Get's the translation key for '<em>Recoverable as a &lt;b&gt;&lt;color=#aaffaaff&gt;Non-Sterile&lt;/color&gt;&lt;/b&gt; item</em>'
			/// </summary>
			public const string @R3_NonSterile_Settings = "R3.NonSterile.Settings";
		}
	}
}
