// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;

namespace DoctorVanGogh.ReclaimReuseRecycle {
    [GeneratedCode("DefGenerator.tt","0.1")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
	public static partial class LanguageKeys {
		public static class @r3 {
			/// <summary>
			/// Get's the translation key for '<em>Reclaim, Reuse, Recycle</em>'
			/// </summary>
			public const string @R3_SettingsCategory = "R3.SettingsCategory";
			/// <summary>
			/// Get's the translation key for '<em>Don’t throw away, recycle for another day.<br />Don’t throw it away, it can be used in some other way.<br />Don’t throw your future away!<br />Just think before you bin it, there could be some use in it!<br />Money grows on trees: Recycle peg legs.<br />Never refuse to reuse.<br />Once is not enough, recycle.<br />Recycle the present, save the future.<br />Recyclers do it over and over again.<br />Waste it once…pay for it twice!<br />When in doubt, don’t throw it out!<br />When you refuse to reuse it’s your Rimworld you abuse.</em>'
			/// </summary>
			public const string @R3_Tagline = "R3.Tagline";
			/// <summary>
			/// Get's the translation key for '<em>Original item</em>'
			/// </summary>
			public const string @R3_OriginalThing = "R3.OriginalThing";
			/// <summary>
			/// Get's the translation key for '<em>&lt;color={1}&gt;{2} {0}&lt;/color&gt;</em>'
			/// </summary>
			public const string @R3_Label = "R3.Label";
			/// <summary>
			/// Get's the translation key for '<em>This is a {0} that was reclaimed from a corpse. It needs to be sterilized before it can be used again.</em>'
			/// </summary>
			public const string @R3_NonSterile_Description = "R3.NonSterile.Description";
			/// <summary>
			/// Get's the translation key for '<em>This is a {0} that was reclaimed from a corpse. It is heavily damaged and need extensive refurbishment and sterilization before it can be used again.</em>'
			/// </summary>
			public const string @R3_Mangled_Description = "R3.Mangled.Description";
			/// <summary>
			/// Get's the translation key for '<em>Multiplier for reclamation status</em>'
			/// </summary>
			public const string @R3_StatsReport_ReclamationMultiplier = "R3.StatsReport_ReclamationMultiplier";
			/// <summary>
			/// Get's the translation key for '<em>The following settings control the health range(s) a corpse&apos;s part needs to have to be recoverable as the respective item type.<br />&lt;size=12&gt;&lt;i&gt;&lt;color=#808080ff&gt;(The recovered parts will have 100% of their hitpoints when harvested at the top end of the range and 50% hitpoints at the bottom.)&lt;/color&gt;&lt;/i&gt;&lt;/size&gt;</em>'
			/// </summary>
			public const string @R3_RangeExplanation = "R3.RangeExplanation";
			/// <summary>
			/// Get's the translation key for '<em>Recoverable as a &lt;b&gt;&lt;color={0}&gt;{1}&lt;/color&gt;&lt;/b&gt; item</em>'
			/// </summary>
			public const string @R3_Settings_Recoverable = "R3.Settings.Recoverable";
			/// <summary>
			/// Get's the translation key for '<em>Complexity</em>'
			/// </summary>
			public const string @R3_Complexity = "R3.Complexity";
			/// <summary>
			/// Get's the translation key for '<em>Max. Complexity</em>'
			/// </summary>
			public const string @R3_MaxComplexity = "R3.MaxComplexity";
			/// <summary>
			/// Get's the translation key for '<em>Mangled</em>'
			/// </summary>
			public const string @R3_Reclamation_Mangled = "R3.Reclamation.Mangled";
			/// <summary>
			/// Get's the translation key for '<em>Non-sterile</em>'
			/// </summary>
			public const string @R3_Reclamation_NonSterile = "R3.Reclamation.NonSterile";
		}
	}
}
